name: Build

on:
  pull_request:
    branches:
      - master

  # Note: Images are currently published via Docker Hub automated build

  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@29e290cf68d621110f6eac3da7914b145c909f63 # v3.0.0
    with:
      image: wetransform/conversion-hale
      tag: ci
