name: Build

on:
  pull_request:
    branches:
      - master

  # Note: Images are currently published via Docker Hub automated build

  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@v2
    with:
      image: wetransform/conversion-hale
      tag: ci
