name: Build

on:
  pull_request:
    branches:
      - master

  # Note: Images are currently published via Docker Hub automated build

  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@733faab9b81e9c64de96ae12a251b3b76111a4eb # v3.1.0
    with:
      image: wetransform/conversion-hale
      tag: ci
