name: Build

on:
  pull_request:
    branches:
      - master

  # Note: Images are currently published via Docker Hub automated build

  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@2c69afaa675dfca01d1bb1acb6150187f0dad05a # v2.3.0
    with:
      image: wetransform/conversion-hale
      tag: ci
