name: Build

on:
  pull_request:
    branches:
      - master

  # Note: Images are currently published via Docker Hub automated build

  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    uses: wetransform/gha-workflows/.github/workflows/dockerfile-build.yml@4fdf015e777b3be01ee5baf8d18441898baf24d8 # v2.2.1
    with:
      image: wetransform/conversion-hale
      tag: ci
